name: "Pull Request Docs Check"

on:
  pull_request:
    paths:
      - ".github/workflows/docs-build.yml"
      - "docs/**"
  push:
    paths:
      - ".github/workflows/docs-build.yml"
      - "docs/**"
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@e781e9af3e80bfe0ea539e4ea46858d51e027214
        with:
          pre-build-command: "pip install -r requirements.txt"
          docs-folder: "docs/"

# vim:ts=2:sw=2:et
